image: dtr.central.docker4sg.saint-gobain.net/ids-tools/docker19.03:alpine3-base-20210220

variables:
  HTTPS_PROXY: "http://proxyout.cly.dtc3.cf.saint-gobain.net:3128"
  HTTP_PROXY: "http://proxyout.cly.dtc3.cf.saint-gobain.net:3128"
  DOCKER_DRIVER: overlay2


stages:
  - build
  - sonarscan
  - deploy

.runner-anchor: &runner-anchor
  environment: Dev
  only:
    - Dev


build-code:
  <<: *runner-anchor
  stage: build
  image : dtr.central.docker4sg.saint-gobain.net/dsig-pub/nodejs12:debian10-slim-20210605
  script:
    - VERSION=$(echo ${CI_COMMIT_TAG} | cut -d \- -f 2)
    - echo $VERSION
    - cd / && cd /$CI_PROJECT_DIR
    - echo $APP_VERSION
    - npm i 
    - npm i -g @angular/cli
    - ng build --prod
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}
    paths:
    - $CI_PROJECT_DIR/dist/*
    

sonar scan:
  <<: *runner-anchor
  stage: sonarscan
  image : dtr.central.docker4sg.saint-gobain.net/ids-tools/sonar-scanner:cli
  before_script:
    - export NO_PROXY=sonar.ids.saint-gobain.com
    - export SONAR_RUNNER_OPTS="-Dhttp.proxyHost=http://proxyout.cly.dtc3.cf.saint-gobain.net -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=sonar.ids.saint-gobain.com"
  script:
    - cd / && cd $CI_PROJECT_DIR
    - sonar-scanner -Dsonar.host.url=https://sonar.ids.saint-gobain.com -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectName=${CI_PROJECT_NAME} -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.sourceEncoding=UTF-8


deploy to azure cloud:
  <<: *runner-anchor
  stage: deploy
  script:
  # build image to deploy code  
  - curl -x "http://proxyout.cly.dtc3.cf.saint-gobain.net:3128" http://ipinfo.io/json
  - docker build  --build-arg RID=$VAULT_RID --build-arg SID=$VAULT_SID --build-arg TARGET=$TARGET --build-arg ACCOUNT_NAME=$ACCOUNT_NAME --build-arg BLOB_NAME=$BLOB_NAME --no-cache -t vault-api:1.0 -f $CI_PROJECT_DIR/Dockerfile .
  # remove docker image post deployment
  - docker rmi vault-api:1.0




    



