image: microsoft/azure-cli

stages:
  - build_deploy

build_deploy:
  stage: build_deploy
  script:
    -   echo "Deploying Angular App to $BLOB_NAME"
#- az login -u $AZ_USER_NAME -p $AZ_USER_PASSWORD
    -   az login --service-principal -u $AZ_APP_ID -p $AZ_SERVICE_PRINCIPAL_PASSWORD --tenant $AZ_SERVICE_PRINCIPAL_TENANT
#- az account set --subscription $AZ_SUBSCRIPTION_ID
#- npm i -g @angular/cli &&  npm install --save-dev @angular-devkit/build-angular
#- /usr/bin/ng build --output-hashing none --base-href https://idsgcpacdn.blob.core.windows.net/idsgcpacdn/
    -   ng build --prod
#- /usr/bin/ng build --output-hashing none --base-href https://idsgcpacdn.azureedge.net/
    -   az storage blob upload-batch -s ./dist/capacity-planning -d $BLOB_NAME --account-key $ACCOUNT_KEY --account-name $ACCOUNT_NAME 
#- az cdn endpoint purge -g $RESOURCE_GROUP --name idsgcpacdn --profile-name idsgcpacdn --content-paths "/*"
  when: manual 
  only:
    -   DEV
